### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by burnpiro**

### CODE REVIEW

**Comment by burnpiro** [comment]
Wygenerowałem plik z licencją MIT

**Comment by tugot17** [comment]
Könnten Sie dem Repo Autoren hinzufügen?

**Comment by burnpiro** [comment]
@all-contributors please add @burnpiro  for design, code, doc and review

**Comment by burnpiro** [comment]
@all-contributors please add @tugot17   for code, data, doc and review

**Comment by burnpiro** [comment]
@all-contributors please add @dkunc  for code, data, doc and review

**Comment by burnpiro** [comment]
@all-contributors please add @NorbertRop  for code, data, doc and review

**Comment by burnpiro** [comment]
@all-contributors please add @tugot17 for code, data, doc and review

**Pull request merged**
